# Generated by Django 3.2.3 on 2021-05-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('category', models.ForeignKey(db_column='category', null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
    ]
