# Generated by Django 3.2.3 on 2021-05-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
