# Generated by Django 3.2.3 on 2021-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_slug_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
