# Generated by Django 3.2.3 on 2021-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
