# Generated by Django 3.2.3 on 2021-05-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to='product/media', width_field=100),
        ),
    ]
