# Generated by Django 3.2.3 on 2021-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_date', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[[1, 'created'], [2, 'in process'], [3, 'complete']], default=1)),
                ('updated_date', models.DateField(auto_now=True)),
                ('description', models.CharField(default='description', max_length=255)),
            ],
        ),
    ]
