# Generated by Django 3.2.3 on 2021-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=models.AutoField(primary_key=True, serialize=False)),
        ),
    ]
